### ISSUE TITLE
How to compile with MinGW.

### ISSUE THREAD

**Issue by Kingwolf123** [maxmind/libmaxminddb#156]
Hello guys.. I am trying to compile with MinGW with mysys 1.0 (32-bit)
`make[2]: Entering directory `/c/Users/Administrator/Desktop/<name>/geolocation/mxlib/src'
/bin/sh ../libtool  --tag=CC   --mode=compile gcc -DHAVE_CONFIG_H -I. -I.. -I../include  -I../include  -O2 -g -g  -fms-extensions -MT maxminddb.lo -MD -MP -MF .deps/maxminddb.Tpo -c -o maxminddb.lo maxminddb.c
libtool: compile:  gcc -DHAVE_CONFIG_H -I. -I.. -I../include -I../include -O2 -g -g -fms-extensions -MT maxminddb.lo -MD -MP -MF .deps/maxminddb.Tpo -c maxminddb.c  -DDLL_EXPORT -DPIC -o .libs/maxminddb.o
In file included from data-pool.h:4:0,
                 from maxminddb.c:4:
../include/maxminddb.h:25:9: error: unknown type name 'ADDRESS_FAMILY'
 typedef ADDRESS_FAMILY sa_family_t;
         ^~~~~~~~~~~~~~
maxminddb.c:18:22: fatal error: ws2ipdef.h: No such file or directory
 #include <ws2ipdef.h>`

What am i doing wrong?

**Comment by horgh** [comment]
It looks like the problem is the ws2ipdef.h header can't be found. That [appears to be](https://sourceforge.net/p/mingw-w64/mingw-w64/ci/d68571c42c670af3a98e3af9c5deb13e5ba85351/tree/mingw-w64-headers/include/ws2ipdef.h) one provided by mingw. I'd guess there is a problem with your  include paths.

You could try to find where that header is and then add it to your include paths with (-I). I would expect it to be in the default include paths though, so maybe there is a problem with your mingw installation. [This looks](http://www.mingw.org/wiki/includepathhowto) like it could be helpful. [This too](https://stackoverflow.com/questions/22243453/mingw-g-doesnt-find-headers-in-its-own-include-directory)

**Comment by Kingwolf123** [comment]
We are using MinGW , not MinGW-64, for building a shared library. MinGW does not have this header.
Also, we have Windows SDK installed, and <headers.h> keep defaulting to the SDK instead of MinGW libraries.

**Comment by horgh** [comment]
I see. Well it looks like we support Mingw-w64 (from looking at #13). If Mingw doesn't have the header, you're probably in uncharted territory unfortunately. I'm not sure what it would take to build with it.

**Comment by Kingwolf123** [comment]
Are your libraries 32 bit compatible.
In linux, when i do ./configure --build-=i686-linux-gnu --host=i686-linux-gnu
Then make, make check, sudo make install, sudo ldconfig.

The produced libraries are still 64-bit, and dont work with:
g++ -m32 -o app *.cpp
The error when i use -m32 is the header file maxminddb.h has error in typedefing mmdb_uint128_t : "unrecognized command before _int128_t"

64bit works without issues on linux.

**Comment by horgh** [comment]
Yes, it should work. Try building this way:

`CFLAGS=-m32 ./configure --host=i686-linux-gnu --disable-shared`

**Comment by horgh** [comment]
(Oops, ignore the `--disable[etc]` I had suggested, that's not relevant)
