### ISSUE TITLE
Sample app doesn't build on OSX (10.9.4)

### ISSUE THREAD

**Issue by sergemeynard-triton** [maxmind/libmaxminddb#34]
Building the 0.5.5 package on OSX 10.9.4 (using _./configure_ and _make_) fails with this error:

```
Making all in bin
gcc -DHAVE_CONFIG_H -I. -I.. -I../include  -I../include  -O2 -g -g  -fms-extensions -MT mmdblookup.o -MD -MP -MF .deps/mmdblookup.Tpo -c -o mmdblookup.o mmdblookup.c
mmdblookup.c:7:10: fatal error: 'malloc.h' file not found
#include <malloc.h>
         ^
1 error generated.
make[2]: *** [mmdblookup.o] Error 1
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2
```

malloc.h is an obsolete include file; this change fixes the issue:

```
#if !defined(__APPLE__)
#include <malloc.h>
#endif
```
